[tool.ruff]
exclude = [
    ".git",
    "docs",
    "setup.py",
]
line-length = 79
lint.ignore = []
lint.select = [
    "A",      # Avoid builtin function and type shadowing
    "ARG",    # Remove unused function/method arguments
    "B",      # bugbear extension
    "C4",     # Check for common security issues
    "COM",    # trailing comma rules
    "D",      # Docstring guidelines
    # "D417",   # Missing argument descriptions in the docstring
    # "E",      # PEP8 errors
    # "ERA",    # No commented out code
    # "F",      # Pyflakes
    "FIX",    # Code should not contain FIXME, TODO, etc
    "I002",   # missing required import
    # "NPY",    # Check all numpy related deprecations
    # "PT",     # Pytest style
    "TID252", # Use absolute over relative imports
    # "W",      # PEP8 warnings
]
