[tool.ruff]
exclude = [
    ".git",
    "docs",
    "examples/",
    "tests/test_data",
    "setup.py",
]
line-length = 79
lint.ignore = [
    "D200",   # One-line docstring should fit on one line with quotes
    "D202",   # No blank lines allowed after function docstring
    "D205",   # 1 blank line required between summary line and description
    "D401",   # First line should be in imperative mood
    "D404",   # First word of the docstring should not be "This"
    "B006",   # Do not use mutable data structures for argument defaults
    "B008",   # Do not perform calls in argument defaults
    "PT018",  # Assertion should be broken down into multiple parts
    "PT019",  # Fixture `_` without value is injected as parameter
]
lint.select = [
    "A",      # Avoid builtin function and type shadowing
    "ARG",    # Remove unused function/method arguments
    "B",      # bugbear extension
    "C4",     # Check for common security issues
    "COM",    # trailing comma rules
    "D",      # Docstring guidelines
    # "D417",   # Missing argument descriptions in the docstring
    "E",      # PEP8 errors
    "ERA",    # No commented out code
    "F",      # Pyflakes
    "FIX",    # Code should not contain FIXME, TODO, etc
    "I002",   # missing required import
    "NPY",    # Check all numpy related deprecations
    "PT",     # Pytest style
    "TID252", # Use absolute over relative imports
    "W",      # PEP8 warnings
]

# Ignore missing docstrings in tests
[tool.ruff.lint.per-file-ignores]
"tests/*" = [
    "D100",
    "D101",
    "D103",
    "D104",
]
[tool.ruff.lint.pydocstyle]
convention = "numpy"